import Foundation

/// What each built-in move works, in the same seven words the suggestion
/// chips use. Display only — nothing programs against it — and kept as a
/// lookup beside the library rather than a stored field, so no routine on
/// disk changes shape for the sake of a label.
///
/// Custom moves carry their own `muscles` string, written by the review.
enum MoveMuscles {
    static func groups(for name: String) -> String? {
        table[MoveAliases.resolve(name)]
    }

    private static let table: [String: String] = [
        "beam front squat": "legs, glutes, core",
        "beam deadlift": "glutes, back, legs",
        "beam good morning": "glutes, back",
        "beam hip thrust": "glutes",
        "beam overhead press": "shoulders, arms",
        "beam row": "back, arms",
        "beam reverse lunge": "legs, glutes",
        "beam floor press": "chest, arms",
        "ring halo": "shoulders, arms, core",
        "ring press-out": "chest, shoulders, core",
        "ring deadlift": "glutes, back, legs",
        "ring goblet squat": "legs, glutes, core",
        "ring row": "back, arms",
        "ring overhead press": "shoulders, arms",
        "ring front raise": "shoulders",
        "ring bicep curl": "arms",
        "ring hammer curl": "arms",
        "ring arnold press": "shoulders, arms",
        "ring behind-back raise": "shoulders, back",
        "kettlebell deadlift": "glutes, back, legs",
        "kettlebell goblet squat": "legs, glutes, core",
        "kettlebell carry": "core, back, arms",
        "band pull-apart": "shoulders, back",
        "band face pull": "shoulders, back",
        "band w raise": "shoulders, back",
        "band external rotation": "shoulders",
        // "neck, core" until the August 2026 audit: "neck" is not one of the
        // seven words the suggestion chips speak, so anything built on the
        // vocabulary mishandled this move.
        "chin tuck": "back, core",
        "wall angel": "shoulders, back, core",
        "dumbbell press": "shoulders, arms",
        "lateral raise": "shoulders",
        "front raise": "shoulders",
        "rear delt fly": "shoulders, back",
        "arnold press": "shoulders, arms",
        "bicep curl": "arms",
        "tricep kickback": "arms",
        "raise the platters": "arms, shoulders",
        "tricep press-back": "arms",
        "floor fly": "chest",
        "around the world": "shoulders, chest",
        "dumbbell shrug": "back, shoulders",
        "upright row": "shoulders, back",
        "overhead extension": "arms",
        "pullover": "chest, back, core",
        "boxer punches": "shoulders, arms, core",
        "beam overhead hold": "core, shoulders",
        "ring half-kneeling overhead hold": "core, shoulders",
        "kettlebell around the body": "core",
        "dumbbell dead bug press": "core, shoulders",
        "dumbbell march": "core",
        "russian twist": "core",
        "standing side bend": "core",
        "forearm plank": "core",
        "side plank": "core",
        "lying leg raise": "core",
        "bicycle crunch": "core",
        "plank shoulder tap": "core, shoulders",
        "dead bug": "core",
        "incline push-up": "chest, arms, core",
        "reverse lunge": "legs, glutes",
        "glute bridge": "glutes",
        "split squat": "legs, glutes",
        "bird dog": "core, back",
        "wall sit": "legs",
        // The audit set (August 2026).
        "beam curl": "arms",
        "beam triceps extension": "arms",
        "beam lateral lunge": "legs, glutes",
        "beam curtsy lunge": "glutes, legs",
        "ring triceps extension": "arms",
        "ring bus driver": "shoulders, arms",
        "ring wrist curl": "arms",
        "ring bridge": "glutes",
        "ring chop": "core, shoulders",
        "ring kickback": "arms",
        "dumbbell floor press": "chest, arms",
        "dumbbell row": "back, arms",
        "zottman curl": "arms",
        "scaption raise": "shoulders",
        "squeeze press": "chest, arms",
        "suitcase deadlift": "glutes, legs, core",
        "tall-kneeling press": "shoulders, core, arms",
        "plank pull-through": "core, shoulders",
        "kettlebell row": "back, arms",
        "kettlebell sumo squat": "legs, glutes",
        "kettlebell rack hold": "core, arms, shoulders",
        "kickstand deadlift": "glutes, legs, back",
        "kettlebell suitcase hold": "core, arms",
        "kettlebell calf raise": "legs",
        "band seated row": "back, arms",
        "band overhead press": "shoulders, arms",
        "superman": "back, glutes, core",
        "one-leg bridge": "glutes, legs",
        "single-leg calf raise": "legs",
        "side leg lift": "glutes",
        "bear hold": "core, shoulders",
        "air squat": "legs, glutes",
        "reverse tabletop hold": "arms, shoulders, glutes"
    ]
}
