import Testing
import Foundation
@testable import WrkTime

/// The library as it was on 22 August 2026, the day the port to
/// `MovementCatalog` began. Every move's name, implement, load, sidedness,
/// kind and cue — and the pattern, position, muscles and form the three
/// lookups answered for it. The port is correct when the catalog reproduces
/// this list exactly; the fixture is regenerated only on purpose.
@Suite("The library snapshot")
struct LibrarySnapshotTests {

    static func line(_ move: Move) -> String {
        let form = MoveForm.notes(for: move.name).map {
            [$0.setUp, $0.movement, $0.feel, $0.wrong, $0.stopIf].joined(separator: "¦")
        } ?? ""
        return [move.name, move.equipment.rawValue, move.kind.rawValue,
                move.loadPounds.map { String($0) } ?? "", move.sidedRaw ?? "",
                MoveTaxonomy.pattern(for: move.name)?.rawValue ?? "",
                MoveTaxonomy.position(for: move.name).map { String($0.rawValue) } ?? "",
                MoveMuscles.groups(for: move.name) ?? "",
                move.cue, form].joined(separator: "\t")
    }

    @Test("Every move reads exactly as it did before the port")
    func unchanged() throws {
        // As a set: the port changed the library's order (the catalog's,
        // then the flow list) and every walk of it is seeded, not positional.
        let now = Set(MoveLibrary.all.map(Self.line))
        let then = Set(LibrarySnapshot.lines)
        #expect(now.count == then.count, "\(now.count) moves now, \(then.count) then")
        for expected in then.subtracting(now) {
            let name = expected.split(separator: "\t").first ?? ""
            Issue.record("\(name) changed or missing:\n  was \(expected)")
        }
        for extra in now.subtracting(then) {
            Issue.record("not in the snapshot: \(extra.split(separator: "\t").first ?? "")")
        }
    }

    /// Writes the current library as a fixture. Run on purpose, never in
    /// the suite — it is how `LibrarySnapshot.swift` was made.
    static func dump(to url: URL) throws {
        let lines = MoveLibrary.all.map(line)
        let body = lines.map { "        \($0.debugDescription)," }.joined(separator: "\n")
        let file = """
        // Generated by LibrarySnapshotTests.dump on 22 August 2026. Do not edit by hand.
        enum LibrarySnapshot {
            static let lines: [String] = [
        \(body)
            ]
        }

        """
        try file.write(to: url, atomically: true, encoding: .utf8)
    }
}
